name: CDN
on:
  push:
    branches: master

jobs:
  release:
    if: ${{startsWith(github.event.head_commit.message, 'Release')}}
    name: Publish releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build bundles
        run: yarn run build
      - name: Upload `uppy` to CDN
        run: yarn run uploadcdn uppy
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/robodog` to CDN
        run: yarn run uploadcdn @uppy/robodog
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/locales` to CDN
        run: yarn run uploadcdn @uppy/locales
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
