name: Deploy uppy.io

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Uppy
        run: yarn run build
      - name: Build website
        run: yarn run web:build
      - name: Prepare deployment
        run: yarn run web:prepare-deploy --quiet
        env:
          DEPLOY_DIR: ${{github.workspace}}/_deploy
      - name: Push to Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _deploy # relative to `github.workspace`
          committer: 'Uppy Bot <uppybot@uppy.io>'
          author: 'Uppy Bot <uppybot@uppy.io>'
          commit_message: Update transloadit/uppy website
          fqdn: uppy.io
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
